### PR TITLE
Batocera fix

### PR DESCRIPTION
**Pull request by nuwonda**
Changes:

* Fixed nominal partition size to 3GB (3096) as Batocera will not be able to update otherwise for all RPI releases
* Fixed partition name to "BATOCERA" instead of "Recalbox"
* Changed default password to mirror Batocera's default password
* Fixed uncompressed tar.xz size value to 1602
* Fixed download size to match current version 5.26 for RPI4 (and for 5.25 for RPI3)
* Added RPI4 Models support info and hex revisions to jsons
* Updated url outdated url to new batocero.org url

### CODE REVIEW

**Comment by nuwonda** [comment]
rpi1 and 2 directories are not updated.

**Comment by matthuisman** [comment]
possible to also update pi1 and pi2 versions?

**Comment by nuwonda** [comment]
done.

**Comment by matthuisman** [comment]
did the os_list.json for each Pi1, Pi2, Pi3 need updating?
I assume the tarballs for those changed?

Nevermind - I see they are still the same :)

**Comment by matthuisman** [comment]
oops that deleted the staging and os_list_v3.
I meant to remove changes from your pull request (not delete them)
By bad for not checking. I have added them back

Can you please test the new files by doing this:

Replace your PINN recovery.cmdline with the below:
`runinstaller quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline no_default_source alt_image_source=http://raw.githubusercontent.com/matthuisman/pinn-os/master/staging.json`

Or download it from here:
https://raw.githubusercontent.com/matthuisman/pinn-os/master/recovery.cmdline

That points pinn to the staging.json to allow testing before it's moved into the live os_list_v3.json

**Comment by nuwonda** [comment]
looking good

**Comment by matthuisman** [comment]
pretty big jump in size for batocera 388137776 > 782392720  (over twice as big)

**Comment by nuwonda** [comment]
been like this ever since i started using this which is why i had to gparted the 1.2GB partition to 3gb every single time, so finally I thought... lets fix it at the root :)

**Comment by nuwonda** [comment]
its the boot.tar.xz size in bytes. (https://batocera.org/upgrades/rpi4/beta/last/) theres a few users on batocera forum who cant update their batocera after installing with noobs/pinn etc since the partition is just too small now.

**Comment by matthuisman** [comment]
Yeh, I was more wondering why his system has over doubled in size in only a few versions.
Must have added a lot of stuff (good stuff hopefully)

**Comment by nuwonda** [comment]
yep! lots of good stuff!

**Comment by nuwonda** [comment]
btw: as the tarball file size keeps changing from version to version (even if its minimal) does it matter what is set as download and unpacked size in the json?

**Comment by matthuisman** [comment]
The sizes are used to calc if it'll fit etc. Download size used for GUI progress. 
So as long as they are pretty close, it should be OK. Safer for them to be over than under

**Pull request merged**
